"""final_schema_definition

Revision ID: 12ba989ed6fa
Revises: 20be46c13fbe
Create Date: 2025-11-09 12:05:17.807995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12ba989ed6fa'
down_revision: Union[str, Sequence[str], None] = '20be46c13fbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('premios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('juego_id', sa.UUID(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.Column('creado_por', sa.String(length=100), nullable=True),
    sa.Column('actualizado_por', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['juego_id'], ['juegos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'partidas', 'premios', ['premio_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'partidas', type_='foreignkey')
    op.drop_table('premios')
    # ### end Alembic commands ###
