"""migracion_inicial

Revision ID: 20be46c13fbe
Revises:
Create Date: 2025-09-21 20:17:18.550286

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20be46c13fbe"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "juegos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("descripcion", sa.String(length=255), nullable=True),
        sa.Column("costo_base", sa.Float(), nullable=False),
        sa.Column("fecha_registro", sa.DateTime(), nullable=False),
        sa.Column("fecha_actualizacion", sa.DateTime(), nullable=False),
        sa.Column("creado_por", sa.String(length=100), nullable=False),
        sa.Column("actualizado_por", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "usuarios",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("nombre_usuario", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=150), nullable=False),
        sa.Column("telefono", sa.String(length=20), nullable=True),
        sa.Column("contrasena_hash", sa.String(length=255), nullable=False),
        sa.Column("edad", sa.String(length=3), nullable=False),
        sa.Column("saldo_inicial", sa.Integer(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=True),
        sa.Column("es_admin", sa.Boolean(), nullable=True),
        sa.Column("fecha_registro", sa.DateTime(), nullable=False),
        sa.Column("fecha_actualizacion", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_usuarios_email"), "usuarios", ["email"], unique=True)
    op.create_index(
        op.f("ix_usuarios_nombre_usuario"), "usuarios", ["nombre_usuario"], unique=True
    )
    op.create_table(
        "boletos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("usuario_id", sa.UUID(), nullable=False),
        sa.Column("juego_id", sa.UUID(), nullable=False),
        sa.Column("numeros", sa.String(length=255), nullable=False),
        sa.Column("costo", sa.Float(), nullable=False),
        sa.Column("fecha_registro", sa.DateTime(), nullable=False),
        sa.Column("fecha_actualizacion", sa.DateTime(), nullable=True),
        sa.Column("creado_por", sa.String(length=100), nullable=False),
        sa.Column("actualizado_por", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["juego_id"],
            ["juegos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "historial_saldo",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("usuario_id", sa.UUID(), nullable=False),
        sa.Column("tipo", sa.String(length=20), nullable=False),
        sa.Column("monto", sa.Float(), nullable=False),
        sa.Column("fecha", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "premios",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("juego_id", sa.UUID(), nullable=False),
        sa.Column("descripcion", sa.String(length=255), nullable=False),
        sa.Column("valor", sa.Float(), nullable=False),
        sa.Column("fecha_registro", sa.DateTime(), nullable=False),
        sa.Column("fecha_actualizacion", sa.DateTime(), nullable=False),
        sa.Column("creado_por", sa.String(length=100), nullable=True),
        sa.Column("actualizado_por", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["juego_id"],
            ["juegos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "partidas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("usuario_id", sa.UUID(), nullable=False),
        sa.Column("juego_id", sa.UUID(), nullable=False),
        sa.Column("costo_apuesta", sa.Float(), nullable=False),
        sa.Column("premio_id", sa.UUID(), nullable=True),
        sa.Column("fecha", sa.DateTime(), nullable=False),
        sa.Column("estado", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["juego_id"],
            ["juegos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["premio_id"],
            ["premios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("partidas")
    op.drop_table("premios")
    op.drop_table("historial_saldo")
    op.drop_table("boletos")
    op.drop_index(op.f("ix_usuarios_nombre_usuario"), table_name="usuarios")
    op.drop_index(op.f("ix_usuarios_email"), table_name="usuarios")
    op.drop_table("usuarios")
    op.drop_table("juegos")
    # ### end Alembic commands ###
